---
title: "IDSml"
author: "Humbert Costas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(randomForest)
library(readr)
library(caret)
library(e1071)

# selected_cols <- c("SrcBytes", "DstBytes", "Land", "WrongFragment", "Urgent", "SameSrvRate", "LoggedIn",  "DstHostSameSrvRate", "DstHostSrvCount","Flag","Attack" )
selected_cols <- c("SrcBytes", "DstBytes", "WrongFragment", "Urgent", "SameSrvRate", "LoggedIn",  "DstHostSameSrvRate", "DstHostSrvCount","Flag","Attack" )


```

## REFERENCES:

List of references:
  
  - Source data [KDD Cup 1999 Data Data Set](https://archive.ics.uci.edu/ml/datasets/kdd+cup+1999+data)
  - A Detailed [Analysis of the KDD CUP 99 Data Set](https://www.ecb.torontomu.ca/~bagheri/papers/cisda.pdf)
  - KDD [download archive](https://www.kdd.org/kdd-cup/view/kdd-cup-1999/Data)
  - Kaggle comunity [notebooks](https://www.kaggle.com/datasets/galaxyh/kdd-cup-1999-data/code) with KDD CUP 99 data set.
  


```{r read_data}
data_full <- read_csv("../data/Book1.csv",
                  col_types = cols(SrcBytes = col_integer(),
                                   DstBytes = col_integer(), Land = col_integer(),
                                   WrongFragment = col_integer(), Urgent = col_number(),
                                   Hot = col_number(), NumFailedLogin = col_integer()))

data <- read.csv (file="../data/Book2.csv",header=T)

```

## Including Plots

You can also embed plots, for example:

```{r feature_selection, echo=FALSE}
data1 <- data[,selected_cols]
# data1 <- data[,c(4:12)]
data1$Attack <- as.factor(data1$Attack)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r train_test, echo=FALSE}
inTrain <- createDataPartition(y=data1$Attack,p=0.01, list=FALSE)
str (data1)
training <- data1[inTrain,]
testing <- data1[-inTrain,]
dim <-nrow (training)
dim(training)
```


```{r train_random_forest, echo=FALSE}
output.forest <- randomForest(Attack ~ ., data = training)
print(output.forest)
plot(output.forest)
```


```{r predict, echo=FALSE}
pred <- predict(output.forest,testing)
str (pred)

```

```{r simple_validation, echo=FALSE}
valid <- testing
valid$Attack <- as.character(valid$Attack)
valid$pred <- as.character(pred)
valid$match <- valid$Attack == valid$pred

table(valid$match)/nrow(valid)*100
```

```{r simple_validation2, echo=FALSE}
table(valid[, c("match", "Attack")])
```

```{r conf_matrix, echo=FALSE}
valid <- testing
cm <- confusionMatrix(pred, testing$Attack)
kableExtra::kable(cm$table)
```

```{r conf_matrix_heatmap, echo=FALSE}
heatmap(cm$table)
```
